version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 10
  install:
    commands:
      - ls -lt
      - npm install -g serverless
      - npm install -D
  pre_build:
    commands:
      - npm run test
  build:
    commands:
      - npm run deploy