service: slack-aws-endpoint

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment: 
    #AWS
    STANDART_QUEUE_URL: "https://sqs.us-east-2.amazonaws.com/744380458397/aws-standard-queue"
    APP_REGION: us-east-2
    #Slack
    SLACK_BOT_TOKEN: "xoxb-489188369799-1804917777168-7uymmw2IUPMTe7y2sYP05czQ"
    SLACK_ERROR_CHANNEL: "C01RP6ALD8R"

functions:
  slack:
    handler: src/index.handler
    events:
      - http:
          path: slack/{any+}
          method: ANY
  slack_airtable_sqs:
    handler: src/LambdaHandlers/sqsSlackHandler.slack_airtable_sqs

plugins: 
  - serverless-offline