service: slack-aws-endpoint

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment: 
    #AWS
    STANDART_QUEUE_URL: ""
    APP_REGION: us-east-2
    #Slack
    SLACK_BOT_TOKEN: ""
    SLACK_BOT_ID: ""
    SLACK_ERROR_CHANNEL: ""

functions:
  slack:
    handler: src/index.handler
    events:
      - http:
          path: slack/{any+}
          method: ANY
  slack_airtable_sqs:
    handler: src/LambdaHandlers/sqsSlackHandler.slack_airtable_sqs

plugins: 
  - serverless-offline