service: sl-connector

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment: 
    #AWS
    APP_REGION: us-east-1
    AWS_USER_TABLE: slack-interactions
    #Slack

functions:
  slack:
    handler: src/index.handler
    events:
      - http:
          path: /slack/{any+}
          method: ANY
  user:
    handler: src/index.handler
    events:
      - http:
          path: /user/{any+}
          method: ANY
  # slack_airtable_sqs:
  #   handler: src/LambdaHandlers/sqsSlackHandler.slack_airtable_sqs

plugins: 
  - serverless-offline